//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityUrunYonetim
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sales
    {
        public int SatisId { get; set; }
        public Nullable<int> UrunId { get; set; }
        public Nullable<int> MusteriId { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual Tbl_Customer Tbl_Customer { get; set; }
        public virtual Tbl_Product Tbl_Product { get; set; }
    }
}
