//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityUrunYonetim
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Customer
    {
        public Tbl_Customer()
        {
            this.Tbl_Sales = new HashSet<Tbl_Sales>();
        }
    
        public int MusteriId { get; set; }
        public string MusteriAd { get; set; }
        public string MusteriSoyad { get; set; }
        public string Sehir { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual ICollection<Tbl_Sales> Tbl_Sales { get; set; }
    }
}
